(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,0,300,600],[302,466,185,128],[302,238,111,226],[473,0,31,99],[415,238,85,151],[302,0,169,236]]}
];


// symbols:



(lib.fourteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.nineteenchease = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.nineteencocktail = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.nineteencrackers = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nineteengrapes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.nineteentomatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.seventeenrollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnuCsQhHABgzgzQgzgyABhIQgBhGAzgzQAzgyBHAAIPdAAQBIAAAyAyQAzAzgBBGQABBIgzAyQgyAzhIgBg");
	this.shape.setTransform(0,5,1.067,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrollovervideo, new cjs.Rectangle(-71.2,-12.7,142.5,35.5), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnuCsQhHABgzgzQgzgyABhIQgBhGAzgzQAzgyBHAAIPdAAQBIAAAyAyQAzAzgBBGQABBIgzAyQgyAzhIgBg");
	this.shape.setTransform(0,5,1.067,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-71.2,-12.7,142.5,35.5), null);


(lib.readytoserve = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhdCEQgKgDAAgJQAAgGAIgDIALgFQADgEABgPQACgQAAgwIAAgeQAAg1gCgPQgCgPgEgDIgJgDQgLgEgBgGQABgFADgDQADgEAJgDIAbgIQANgEAGAAQAGAAACADQADADgBAHIAAAJIABAEIAAABIAIgFIAIgFQAMgJAKgFQALgEALAAQAkAAAXAaQAXAbAAAqQAAAtgaAeQgaAegnAAQgQAAgHgFQgGgFAAgHQAAgEADgEQADgDAGAAIAFABIAGABQAVAAANgSQAOgSAAgdQAAghgPgUQgNgUgXAAQgTAAgMALQgLALAAAdIAAB6IABAUQABAHADADQACADAJACIAHACIAEAEIABAGQAAAHgLADQgLADgbAAQgcAAgKgDg");
	this.shape.setTransform(52.7,30.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AicBgQgKgDAAgJQAAgGAKgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigBgLQgDgKgDgDIgJgEQgMgDAAgHQAAgEADgDIAMgHIAdgJIATgEQAFAAADADQACADABAHIAAALIAAABIAAACIABABIABAAIABgBIAFgDIACgDQAXgVAYAAQAIAAAJADQAIADAIAEQAGAGAIAIQAHAJABAAQAEAAAEgGIAJgJQANgLAJgDQAJgEAMAAQAWAAAQAJQASAJAHAQQAIASABA4IAAATIAAALIAAAJQgBAKACAFQADAFAEADIAGACQAJAEAAAGQAAAJgJADQgJACgeAAQgcAAgJgCQgKgEAAgGQAAgIAKgEIAHgDQAFgDADgJQACgKAAgXQAAg4gJgQQgHgPgUAAQgXAAgKAUQgKAUAAAtIAAALQAAAVADAGQACAHAEADIAGACQAJAEAAAGQAAAJgJADQgJACgdAAQgaAAgKgCQgJgEAAgGQAAgIAKgDIAHgEQAEgCACgIQABgIAAgWQABg8gIgQQgIgQgVAAQgKAAgJAGQgKAHgEAKQgFAIgBARQgCAOAAAlQAAASACAGQABAHAFACIAGAEQAKADAAAIQABAGgKAEQgKADgZAAQgeAAgJgDg");
	this.shape_1.setTransform(24,27.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgiCKQgJgDAAgJQAAgGAJgEIAGgCQAEgDACgGQADgHAAgOIgBgNIAAgQIAAgUQAAgegCgJQgBgJgEgCIgJgDQgMgEABgGQAAgFADgDQAEgEAIgDIAdgJIAUgEQAFAAADAEQACAEAAAIIAAAMIgBAJIgBAwIAAABIgBAwQAAASACAIQACAHADACIAIAEQAJADAAAIQAAAHgJADQgKADgZAAQgcAAgKgDgAgXhhQgJgGAAgLQAAgLAKgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgMAAQgNAAgIgHg");
	this.shape_2.setTransform(0.9,23);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("Ag6BgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgBgKgFgDIgIgEQgMgDAAgHQABgEADgEQADgDAJgDIAagIIARgEQAKAAACAaIABAEIABABQAKgQALgIQAKgIALAAQAOAAAHAIQAIAIAAAOQAAANgFAIQgHAIgKAAIgKgCIgIgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARABAIQADAJAFACIAHADQAMADAAAJQAAAGgLAEQgLADgZAAQgeAAgJgDg");
	this.shape_3.setTransform(-11.4,27.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAbCLQgKgEAAgHQAAgHAKgEIAHgDQAFgDABgIQACgIAAgVQAAg+gHgOQgIgQgVAAQgJAAgKAGQgJAGgFAKQgEAIgCAPQgBAPgBAmQABATABAGQABAHAFACIAHADQAKAEAAAHQAAAHgJAEQgKADgZAAQgeAAgKgEQgJgDAAgIQAAgHAJgDIAFgCQAFgDADgIQACgIAAgWIAAgfIAAgdIgBhYQgBgVgEgEQgCgCgLgEQgLgDAAgHQAAgFAEgDQAFgEARgHIAUgFIASgCQAGAAADAEQACADAAAJIAAAIIgBBNIAAAKIAAAEIADACIAFgEIAGgIQAKgKALgFQAJgEANAAQAhAAAQAVQARAWAAAqIAAASIAAAjIAAALQAAAKACAEQACAEAEADIAFACQAJADAAAHQAAAIgJADQgJAEgeAAQgaAAgJgDg");
	this.shape_4.setTransform(-31.1,23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgvCMQgWgGgOgIQgHgEgFgRQgFgQAAgWQAAgIAEgGQADgEAGAAQAJAAAKASIAEAIQANAVAOAKQAPAJATAAQAVAAAPgMQAPgNAAgSQAAgbg6gZIgFgDQgwgTgOgSQgQgQAAgcQAAgiAagWQAZgXApAAIAWACIAbAGIAIgFIAGgCQAFAAADADQAFADADAIQAHALAEANQADAMABAKQAAAGgEAEQgDAEgFAAQgKAAgKgOIgDgEQgLgPgNgGQgNgHgQAAQgVAAgMAKQgMAKAAASQAAAPAKALQAKALApARIAJADQAiAPAPANQALAKAFANQAGANAAAPQAAAogbAWQgcAWgxAAQgXAAgVgEg");
	this.shape_5.setTransform(-53.5,23.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_6.setTransform(125.2,-18.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgUBRQgLgTgbg/IgLgdQgPgkgIgFIgGgDQgLgEAAgHQAAgHAKgDQAKgEAfAAQAaAAAJAEQAKADAAAHIgBAGIgEAEIgGACQgIAEAAAEIAEAQIAPAlIAPAlQAFAIACAAQADABADgGIAJgRIAVgwQAHgTAAgGIgCgHIgEgFIgFgBQgJgEAAgGQAAgHAJgDQAIgEAYAAQAUAAAJAEQAIACAAAIQAAAHgKAEIgHACQgJAEgQAnIgFALIgIASQgsBkgMgBQgIAAgLgSg");
	this.shape_7.setTransform(105,-18.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("Ag6BgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgBgKgFgDIgIgEQgMgDAAgHQABgEADgEQADgDAJgDIAagIIARgEQAKAAACAaIABAEIABABQAKgQALgIQAKgIALAAQAOAAAHAIQAIAIAAAOQAAANgFAIQgGAIgLAAIgKgCIgIgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARABAIQADAJAFACIAHADQAMADAAAJQAAAGgLAEQgLADgZAAQgeAAgJgDg");
	this.shape_8.setTransform(88,-18.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_9.setTransform(70,-18.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgvCMQgWgGgOgIQgHgEgFgRQgFgQAAgWQAAgIAEgGQADgEAGAAQAJAAAKASIAEAIQANAVAOAKQAPAJATAAQAVAAAPgMQAPgNAAgSQAAgbg6gZIgFgDQgwgTgOgSQgQgQAAgcQAAgiAagWQAZgXApAAIAWACIAbAGIAIgFIAGgCQAFAAADADQAFADADAIQAHALAEANQAEAMAAAKQAAAGgEAEQgDAEgFAAQgKAAgKgOIgCgEQgMgPgNgGQgNgHgQAAQgVAAgMAKQgMAKAAASQAAAPAKALQAKALApARIAJADQAiAPAPANQALAKAFANQAGANAAAPQAAAogbAWQgcAWgxAAQgXAAgVgEg");
	this.shape_10.setTransform(48.5,-22.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AglAUQgGAAgCgCQgEgCAAgGIACgIIAFgLQADgFACgCQADgCAIAAIAKAAIAQAAIAhgBIAFAAQAGAAADACQADACgBAFQAAALgFAJQgGAJgJAAIgJAAIgLgBIgqACIgEAAg");
	this.shape_11.setTransform(30.8,-18.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAbAbQAaAbAAArQAAAsgcAeQgdAegpAAQgqAAgcgdgAgkg5QgMAQAAAaQAAAlAQAaQAQAaAXAAQATAAAMgQQALgQAAgbQAAgkgPgaQgSgagWAAQgSAAgMAQg");
	this.shape_12.setTransform(13.4,-18.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgCgLAAgdIAAhnIgSAAIgGgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQABACABAFIAAAFQAAAFgCACQgDACgEAAIgoAAIgDACIgBAEIAABfQAAAZAEAHQAFAGALAAQAGAAAKgDIANgDQAEAAADACQACADAAAEQAAAKgPAKQgRAKgVAAQgLAAgKgDg");
	this.shape_13.setTransform(-4.2,-20.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AglAUQgHAAgCgCQgCgCAAgGIABgIIAFgLQACgFADgCQADgCAIAAIAJAAIARAAIAhgBIAFAAQAGAAADACQACACABAFQAAALgHAJQgFAJgKAAIgJAAIgKgBIgrACIgDAAg");
	this.shape_14.setTransform(-17.7,-18.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AhZB/QgIgHgBgNQAAgKAHgGQAHgHAJAAIAJACIAGADIAFAIQAFAHAEABQAJgBALgOQAKgOAAgPQAAgRgOgeIgBgFIgghDIgSglQgDgHgLgGQgHgCgCgCQgDgEAAgDQAAgJALgDQAKgEAcAAQAcAAAKAEQAJADAAAHIgBAGIgDAEIgHADQgIADAAAEIAEAOIAPAnIAQAkQAFAJADAAQACAAAEgJIANgfIAOgmQAEgOAAgFQABgFgLgGQgLgGAAgFQAAgHAJgDQAIgCAWgBQAYAAAHAEQAIADAAAHQAAAHgLADIgIADQgLAFgLAhIgHAPIgYA+QggBQgUAZQgUAXgcAAQgOAAgKgIg");
	this.shape_15.setTransform(-33.8,-14.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AhUB1QgXgaAAgqQAAgvAbgdQAageApABIANABQAGACAEAEQADAEAAAGQAAAJgNABIgFgBIgFAAQgWgBgMATQgNAQAAAeQAAAhAOAVQAOATAWAAQATABALgLQALgMAAgWIAAg0IAAhZQAAgNgCgFQgDgGgHgCIgFgCQgMgDAAgHQAAgFAFgEQAEgEAPgFIAWgGIASgCQAGAAADAEQADADAAAJIAAAJIgCB3IABBRQABASADADIAOAEQAKADAAAGQAAAKgcAIIgTAGIgPABQgFAAgDgDQgCgCAAgHIAAgJIgBgEIgBgCIgGAEIgIAHQgMAIgKAFQgLAEgMAAQgkAAgXgag");
	this.shape_16.setTransform(-54.5,-22.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgTAXgLQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_17.setTransform(-76.7,-18.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_18.setTransform(-97.4,-18.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AApBgQgSg9gOgNQgMgMgUAAQgPAAAAgMQAAgMAMAAQAgAAAPgNQAQgMAAgaQAAgagQgNQgQgNgdAAQgPAAgGACQgFACgCAGIgCARIgBAnIAABVIABA5QABAOAEADIAIAEQAMAEAAAIQAAAIgKAEQgLADgfAAQgeAAgKgDQgLgEAAgIQAAgIAMgFIAIgEQAEgDACgXQACgXAAg8IgChJQgBgcgDgDQgCgDgKgFQgKgEAAgHQAAgHAGgDQAFgEANAAIAqAAIAngBIAegBQAqAAAWATQAXASAAAiQAAAZgPATQgPASgbAIIAAACQAVAEAMANQAMAMAJAfIAFAUQAIAeALAAIAGgBIAHAAQADAAADADQADADAAAEQAAAJgLAGQgLAGgSAAQgnAAgNgug");
	this.shape_19.setTransform(-121,-22.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.readytoserve, new cjs.Rectangle(-137.4,-47.9,274.9,95.8), null);


(lib.partystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag0A/IgFgBQAAgBgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhyQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAvAAIAMABIANAEQAMAEAKAIQAJAJAFALQADAGABAGQABAHAAAGQAAAOgFAMIgGALIgJAJIgKAHIgLAFQgMAFgNAAgAgigmQgCACAAADIAABFQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAIAEACIAXAAQAIAAAIgDQAIgDAGgFQAGgFAEgIQADgHAAgKQAAgIgDgIQgEgHgGgGQgGgFgIgDQgIgDgIAAIgWAAQgDAAgDACg");
	this.shape.setTransform(110.4,-0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(97.2,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABABAEIAABbQgBABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_2.setTransform(85.3,-0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAfBAIgCgBIgDgCIgBgBIgWghIgDgEQgCgBgEgBIgQAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAeQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgEACIgFAAIgEAAQgEAAgCgCQgCgCAAgDIAAh0QAAAAAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIAEgBIA1AAQAJAAAIADQAJADAFAGQAHAFADAIQADAHAAAKQAAALgEAHQgEAFgFAEIgJAHQgDADAAADIAAACIAEAIIAIAKIAHAKIACAGQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgFADIgEAAgAgZgoQgDABAAAFIAAAcQAAADADABQACACADAAIAZAAQAGAAADgBQAFgBADgDQAEgCACgEQABgEAAgGQAAgKgHgFIgIgEIgJgBIgZAAIgFABg");
	this.shape_3.setTransform(74.1,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAuA/IgHAAQgDgBgCgDIgHgRIgCgDQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCABIgCACIgBABIgGARIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCIgBgCIAzh2QAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIAxB1IAAABQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgEABIgFABgAgBgTIgBABIgBAEIgDAGIgDAHIgDAGIgCAGIgBACIABADIACABIAZAAIACgBIABgCIgCgGIgEgJIgEgLIgDgGIgDgBg");
	this.shape_4.setTransform(61,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_5.setTransform(49.7,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgcA8QgNgFgKgJIgBgDIgBgCIACgEIADgFIAFgCIAEgCQADAAADADIAIAFIALAFQAGACAIAAIAJgBQAFAAAFgCQAEgDADgDQADgDAAgHQAAgEgDgEQgEgDgFgBIgNgCIgOgDIgPgDQgHgCgGgDQgGgDgDgHQgEgGAAgKQAAgJAFgHQAFgIAIgFQAIgEAJgDQAJgCAHAAIANABIAMADIAMAFIAKAHIABACIAAACIgBAFIgEAEIgFADIgFABIgDAAQgHgHgHgCQgIgEgIAAIgIABQgFABgEACQgEACgCADQgDADAAAFQAAAIAGACQAGAEAJABIASACQALABAJAEQAJADAGAHQAGAGAAANQAAALgFAIQgGAIgIAGQgIAFgJACQgKACgJABQgNAAgOgGg");
	this.shape_6.setTransform(38.4,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgEBBIgDAAIgCgCIgBgCIAAgtIgCgHIgDgHIgkg2IAAgCIABgEIAEgDIAFgCIAEgBIAEABIADACIAZApIADADIACAAIADgBIACgCIAZgpIAEgDIAEgBIAEABIAFACIAEADQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAABIAAACIgkA3IgEAHIAAADIgBADIAAAtQgCAEgEAAIgGABg");
	this.shape_7.setTransform(21.2,-0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AACA/IgDAAIgHgBQgCgBAAgEIAAhcQAAgBgBAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgJAAIgGAAQgDAAgBgDQgCgCAAgDIAAgEIABgFIACgDIADgBIBXAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgaAAQgCAAgDACQgCABAAAEIAABbQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDACg");
	this.shape_8.setTransform(10.3,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAgBAIgDgBIgDgCIgBgBIgWghIgDgEQgDgBgDgBIgPAAQgBABgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAABgBAAQAAABAAAAQAAABAAABIAAAeQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAIgFACIgFAAIgEAAQgEAAgCgCQgCgCAAgDIAAh0QAAAAAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIAEgBIA1AAQAJAAAIADQAJADAFAGQAHAFADAIQADAHAAAKQAAALgEAHQgEAFgFAEIgJAHQgEADAAADIABACIAFAIIAHAKIAGAKIADAGQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgFADIgEAAgAgagoQgCABAAAFIAAAcQAAADACABQADACADAAIAaAAQAEAAAFgBQAEgBAEgDQADgCABgEQACgEAAgGQAAgKgGgFIgIgEIgJgBIgaAAIgGABg");
	this.shape_9.setTransform(-0.8,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAuA/IgHAAQgDgBgCgDIgHgRIgCgDQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCABIgCACIgBABIgGARIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCIgBgCIAzh2QAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIAxB1IAAABQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgEABIgFABgAgBgTIgBABIgBAEIgDAGIgDAHIgDAGIgCAGIgBACIABADIACABIAZAAIACgBIABgCIgCgGIgEgJIgEgLIgDgGIgDgBg");
	this.shape_10.setTransform(-13.9,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgsBAQgFAAgCgEIAAh3QAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAIADgBIA2AAQAJAAAIADQAIADAGAEQAGAGAEAHQADAIAAAIIAAAHIgCAGQgFALgIAGQgIAFgKACQgLACgKAAIgVgBIgCABIgCABIgBAEIAAAoIgDACIgEABIgFABgAgbgmQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAAWIABADQABABAAAAQABAAAAABQABAAAAAAQABAAAAAAIAfAAIAIgBQADgBADgCQADgCACgEQACgDAAgFQAAgDgCgDQgCgDgDgCIgGgDQgDgCgDAAIggAAQgDAAgCADg");
	this.shape_11.setTransform(-25.6,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_12.setTransform(-43.5,-0.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgsBAIgEgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIAAh4IADgCIAEgCIAFAAIAEAAQAFAAACAFIAAAoQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAIArAAQADAAACgCQACgCAAgDIAAgoQADgEADAAIAIgBIAGABIAEAEIgBB3QgBAEgEAAIgHAAIgGAAIgFgEIAAgsQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAgBgBQgCgCgCAAIgqAAQgDAAgDADQgCACAAADIAAArQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgEABIgFABg");
	this.shape_13.setTransform(-56.9,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_14.setTransform(-69.1,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_15.setTransform(-84.8,-0.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAAAAAABIAAARQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_16.setTransform(-95.5,-0.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgKBAQgGgBgGgDQgGgCgFgDIgLgIQgFgEgDgGIgGgLQgGgNAAgNIABgNIAFgMQAFgNAJgIIALgIIALgFIAMgFIANgBIAOABQAIACAGADQAOAGAJAMIAAABIgBAFIgEAEIgFAEIgEACQgDAAgDgDIgGgGQgEgDgHgDQgFgCgJAAQgIgBgIAEQgHADgHAGQgFAGgEAIQgDAIAAAIQAAAJADAHQAEAIAFAHQAHAFAHAEQAIAEAIgBIAJgBIAJgCIAHgDIAGgHIAAgCQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgDgCIgXAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAIgBgEIgBgFIAAgEIABgEQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAIA2AAIABABIACACQACAFABAFIAAAHIgCAEQgDAKgHAHQgGAIgHAFQgJAFgJACQgJAEgKAAQgGgBgHgBg");
	this.shape_17.setTransform(-109.9,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partystarted, new cjs.Rectangle(-119.1,-11.2,238.3,22.4), null);


(lib.partyperfect = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgOBlIgVgFIgFAFIgGABIgEgBIgEgDQgGgFgGgQQgFgQgBgOQAAgGADgEQAEgEAFAAQAJAAAJAPIAHAMQAGAIAKAEQAKAEAKABQAOgBAHgGQAHgGAAgLQAAgQgfgQIgLgGQgfgPgKgLQgLgNAAgSQAAgaASgPQARgQAdAAIAMAAIAOADIAJgEIAGgBQAJABAKAPQAIAPAAAQQAAAHgDAFQgCADgHAAQgEAAgEgDQgEgEgGgKQgHgMgIgEQgIgFgKAAQgLAAgHAGQgGAHAAAKQgBAIAIAHQAGAHAXAMIADABQA2AagBAgQABAagVATQgVASgfAAg");
	this.shape.setTransform(116.7,27.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AggCLQgKgDAAgJQABgGAHgDIAKgGQAEgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgBgPQgCgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAEgDAOgFIAagHIATgDQAGAAACADQACAEAAAKIAAAOQgCBFAABGIABBBQABAOAEAEIALAGQAIADABAIQAAAGgKAEQgKADgZAAQgcAAgKgDg");
	this.shape_1.setTransform(102.8,23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AALAVIgXg8QgLgbgJgFIgGgDQgLgEAAgHQAAgHAKgDQAKgEAeAAQAaAAAKAEQAJADAAAHIgBAGIgEAEIgGACQgIAEAAAEIADANIAQAoIARAlQAEAIADAAQACABAEgGIAIgRIAVgwQAHgTAAgGIgBgHIgFgFIgFgBQgJgEAAgGQAAgHAJgDQAIgEAYAAQAUAAAJAEQAIACAAAIQAAAHgKAEIgHACQgJAFgRAoIgEAJIgIASQgsBkgNgBQgNAAgihOgAhxALIgGgMIgMghQgNgggIgFIgGgDQgLgEAAgHQAAgHAJgDQAKgEAfAAQAbAAAJAEQAJADAAAHIgBAGIgDAEIgHACQgIAEAAAEIAFAQIAOAlIAQAkQAFAKADgBQAGABAFgMIAGgOIAFgGQACgCAFAAQAEAAADADQADADAAAEQAAAGgGAKQgUAsgJAQQgJANgGAAQgOABgmhZg");
	this.shape_2.setTransform(82.1,27.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAaAbQAbAbAAArQAAAsgcAeQgdAegqAAQgpAAgcgdgAgkg5QgMAQAAAaQAAAlARAaQAQAaAWAAQATAAAMgQQAMgQAAgbQAAgkgQgaQgRgagXAAQgTAAgLAQg");
	this.shape_3.setTransform(55.1,27.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgNCMIgngCIgSABIgWAAQgOAAgGgEQgHgDAAgHQAAgIAKgDQAKgFACgDQADgDACgdIABhLIgBhIQgCgdgDgDQgCgDgKgEQgKgFAAgHQAAgHAGgEQAGgDALAAIAVABIAWAAIAngBIAegBQAqAAAWARQAWARABAhQAAAagQARQgQAQgeAFQAmAEAUASQAVASAAAgQAAAkgZAVQgbATgtABgAgdhvQgGABgCADQgDAFgBATIgCA3IAABQIACAmQABAKADAGQACAEAJADQAKACAQAAQAggBAQgNQAQgNAAgZQAAgbgSgNQgTgNgjgBQgQABAAgLQAAgOAQAAQAaAAAQgMQAQgLAAgaQAAgYgPgNQgQgMgeAAg");
	this.shape_4.setTransform(30.8,23.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("Ag+B0QgcgdAAgpQAAgtAcgdQAdgdArAAQAlAAAWAVQAWAWAAAjQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgSgMgMQgNgNgRAAQgXAAgLAUQgLATAAAcQAAAfAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcgAgWhSQgFgGAAgFIABgCIAFgEIBAgoIAGgDIAFgBQAFAAAGAIQAFAIAAAHQAAAGgLAFIgBAAIhEAfIgDABIgCABQgDAAgEgGg");
	this.shape_5.setTransform(-3.1,23.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgCgLAAgdIAAhnIgSAAIgGgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQACACAAAFIAAAFQAAAFgDACQgBACgFAAIgoAAIgDACIgBAEIAABfQAAAZAEAHQAFAGALAAQAGAAAKgDIANgDQAEAAADACQACADAAAEQAAAKgPAKQgRAKgVAAQgLAAgKgDg");
	this.shape_6.setTransform(-20.1,25.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgiCKQgJgDAAgJQAAgGAJgEIAFgCQAFgDADgGQABgHAAgOIAAgNIAAgQIAAgUQAAgegBgJQgCgJgEgCIgJgDQgLgEAAgGQAAgFADgDQADgEAJgDIAdgJIATgEQAGAAACAEQACAEAAAIIAAAMIAAAJIgCAwIAAABIAAAwQAAASABAIQACAHAFACIAHAEQAKADAAAIQAAAHgKADQgKADgYAAQgdAAgKgDgAgXhhQgJgGABgLQAAgLAJgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgMAAQgNAAgIgHg");
	this.shape_7.setTransform(-32.6,23);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AhUB1QgXgaAAgqQAAgvAbgdQAageApABIANABQAGACAEAEQADAEAAAGQAAAJgNABIgFgBIgFAAQgWgBgMATQgNAQAAAeQAAAhAOAVQAOATAWAAQATABALgLQALgMAAgWIAAg0IAAhZQAAgNgCgFQgDgGgHgCIgFgCQgMgDAAgHQAAgFAFgEQAEgEAPgFIAWgGIASgCQAGAAADAEQADADAAAJIAAAJIgCB3IABBRQABASADADIAOAEQAKADAAAGQAAAKgcAIIgTAGIgPABQgFAAgDgDQgCgCAAgHIAAgJIgBgEIgBgCIgGAEIgIAHQgMAIgKAFQgLAEgMAAQgkAAgXgag");
	this.shape_8.setTransform(-48.8,23.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAqBiQgDgDAAgHIAAgNIAAgBIgBAAQgCAAgFAEIgDAEQgJAIgLAFQgLAFgOAAQgPAAgMgGQgNgFgJgKQgJgLgEgQQgDgPAAgoIAAgNIAAgPIAAgEQAAgQgDgEQgBgFgIgCIgHgDQgLgCAAgIQAAgEAEgEQADgCAOgGIAbgGIAUgDQAFAAADAEQACADAAAJIAAAIIgCBIQAAAmAIAPQAIAQAUAAQAVgBAJgTQAKgTAAgvIAAgPQAAgPgCgEQgDgFgGgCIgIgDQgLgCAAgIQAAgEAEgDQAEgDANgGIAagGIAUgDQAHAAACAEQACADAAAJIAAALIgDBPIABAhIABAMQABAIALAEIADABQALAEAAAHQAAAEgEADQgDADgIADIgbAJQgOAEgHAAQgGAAgCgDg");
	this.shape_9.setTransform(-72.6,27.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("Ag6BgQgKgDAAgJQAAgGAKgEIAFgCQAFgDACgHQADgGgBgOIAAgOIAAgPIAAgMQAAgigBgLQgCgKgFgDIgIgEQgMgDAAgHQABgEADgEQADgDAJgDIAagIIARgEQAKAAADAaIAAAEIABABQAKgQAKgIQALgIAMAAQANAAAHAIQAJAIgBAOQABANgHAIQgGAIgKAAIgLgCIgHgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARABAIQACAJAGACIAIADQALADAAAJQAAAGgLAEQgLADgZAAQgdAAgKgDg");
	this.shape_10.setTransform(-90.8,27.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgdCHQgagKgUgRQgWgVgMgcQgMgdAAghQAAgbAIgYQAIgXAPgTQATgXAbgMQAcgMAfAAIAYACIAlAIIAEgCIAPgDIAGACIAFAGQAHAKAEAPQAEAOAAAMQAAAIgDAEQgDAEgGAAQgJAAgPgRIgMgOQgKgLgQgFQgPgGgSAAQgmAAgVAaQgWAaAAAtQAAA4AcAlQAbAlAqAAQARAAAPgGQAPgFAKgKIAJgLQAIgLAGAAQAGAAADAFQADAFAAAJQAAASgFALQgGAKgIAAIgCAAIgDgBQgSAKgSAEQgSAFgUAAQgbAAgagJg");
	this.shape_11.setTransform(-111.7,23.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgCgLAAgdIAAhnIgSAAIgGgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQACACAAAFIAAAFQAAAFgDACQgBACgFAAIgoAAIgCACIgCAEIAABfQAAAZAEAHQAFAGALAAQAGAAAKgDIANgDQAEAAADACQACADAAAEQAAAKgPAKQgRAKgVAAQgLAAgKgDg");
	this.shape_12.setTransform(107.3,-20.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag9BJQgbgdAAgpQAAgsAdgdQAdgeAqAAQAgAAAWARQAXAQAAAXQAAAJgHAFQgFAGgLAAQgJAAgGgFQgGgEgHgQQgGgOgHgGQgIgFgLAAQgWAAgMARQgNAQAAAeQAAAiASAVQARAWAbAAQAKAAAJgDQAJgCAGgFIAIgGQAKgIAHAAQADAAADACQACADAAAEQAAAFgEAGQgEAHgHAGQgPANgQAGQgQAHgUAAQgoAAgbgcg");
	this.shape_13.setTransform(90.5,-18.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_14.setTransform(70.3,-18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("Ag2CLQgKgDAAgIQAAgGAKgDIAFgDQAFgCACgHQABgGAAgQIAAgTIAAhdIgWAAQgEAAgBgCQgCgCAAgFIAAgEQAAgFACgDQACgBAEAAIAVAAIgCgQIgCgNQAAgeASgQQASgRAfABQAWgBAOALQANAJAAAQQAAAIgEAFQgGAFgJAAQgGAAgFgDQgFgCgDgFIgDgHQgIgOgLgBQgHABgEAEQgEAFAAAHIAEAWQADARABAOIAcAAQAFgBACACQABACAAAGIAAAEQAAAFgBACQgCACgFAAIgcAAIAABjQAAAZABAHQACAIAEACIAIADQALADAAAJQAAAGgJAEQgKACgbAAQgcAAgKgCg");
	this.shape_15.setTransform(56.3,-22.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("Ag6BgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgBgKgEgDIgJgEQgMgDAAgHQAAgEAEgEQADgDAJgDIAagIIARgEQAKAAACAaIABAEIABABQAKgQALgIQAKgIALAAQAOAAAIAIQAHAIAAAOQAAANgFAIQgHAIgKAAIgKgCIgIgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARACAIQABAJAGACIAHADQAMADAAAJQAAAGgLAEQgKADgaAAQgeAAgJgDg");
	this.shape_16.setTransform(42.2,-18.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_17.setTransform(24.2,-18.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AhjCJQgMgEAAgIQAAgIANgEIAIgFQAEgCACgYQABgWAAg9IgBhIQgBgdgDgDQgDgDgKgEQgJgFgBgHQABgHAFgEQAGgDAMAAIAUABIAXAAIAmgBIAegBQAsAAAWASQAWASgBAmQAAAogbAWQgaATgzAAQgTABAAgNQAAgNAQgBQAYABAQgNQAPgNgBgdQAAgagPgMQgQgNgegBQgOABgGACQgGACgCAFIgCASIAAAoIAABUIABA3QABAPAEADIAIAEQAMAEAAAIQAAAIgKAEQgLADgfABQgegBgKgDg");
	this.shape_18.setTransform(2.9,-22.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AglAUQgGAAgCgCQgDgCgBgGIADgIIAEgLQADgFACgCQADgCAIAAIAJAAIARAAIAhgBIAFAAQAGAAADACQACACAAAFQAAALgFAJQgHAJgJAAIgJAAIgKgBIgrACIgDAAg");
	this.shape_19.setTransform(-15.8,-18.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AhZB/QgJgHAAgNQABgKAGgGQAHgHAKAAIAIACIAGADIAFAIQAFAHAEABQAKgBAKgOQAKgOAAgPQAAgRgNgeIgDgFIgfhDIgSglQgCgHgMgGQgHgCgCgCQgCgEgBgDQAAgJAKgDQALgEAcAAQAdAAAJAEQAKADAAAHIgCAGIgEAEIgHADQgHADAAAEIAEAOIAQAnIAPAkQAFAJACAAQADAAAEgJIANgfIAOgmQAFgOAAgFQAAgFgMgGQgKgGgBgFQABgHAIgDQAJgCAWgBQAYAAAHAEQAJADgBAHQABAHgLADIgIADQgMAFgMAhIgFAPIgZA+QgfBQgVAZQgUAXgcAAQgOAAgKgIg");
	this.shape_20.setTransform(-31.9,-14.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgCgLAAgdIAAhnIgSAAIgGgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQACACAAAFIAAAFQAAAFgDACQgBACgFAAIgoAAIgDACIgBAEIAABfQAAAZAEAHQAFAGALAAQAGAAAKgDIANgDQAEAAADACQACADAAAEQAAAKgPAKQgRAKgVAAQgLAAgKgDg");
	this.shape_21.setTransform(-48.4,-20.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("Ag6BgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgBgKgFgDIgIgEQgMgDAAgHQABgEADgEQADgDAJgDIAagIIARgEQAKAAACAaIABAEIABABQAKgQALgIQAKgIALAAQAOAAAHAIQAIAIAAAOQAAANgFAIQgHAIgKAAIgKgCIgIgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARABAIQADAJAFACIAHADQAMADAAAJQAAAGgLAEQgLADgZAAQgeAAgJgDg");
	this.shape_22.setTransform(-62.3,-18.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgTAXgLQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_23.setTransform(-80.2,-18.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("AhjCJQgMgEAAgIQAAgIANgEIAIgFQAEgCACgYQACgWAAg9IgChIQgBgdgDgDQgDgDgJgEQgLgFAAgHQABgHAFgEQAGgDAMAAIAUABIAXAAIAmgBIAfgBQArAAAWASQAWASgBAmQAAAogbAWQgaATgzAAQgTABAAgNQAAgNAQgBQAYABAQgNQAOgNAAgdQAAgagPgMQgQgNgegBQgOABgGACQgGACgCAFIgCASIgBAoIAABUIACA3QABAPAEADIAIAEQAMAEAAAIQAAAIgKAEQgLADgfABQgegBgKgDg");
	this.shape_24.setTransform(-101.8,-22.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyperfect, new cjs.Rectangle(-127.2,-47.9,254.5,95.8), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaA1IgZhVIgBAAIgZBVIgQAAIgehpIAQAAIAXBTIAZhTIAQAAIAYBTIABAAIAXhTIAQAAIggBpg");
	this.shape.setTransform(34.5,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA3IgLgDQgKgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHQAHgIAKgEIALgDIALgBQAMAAAKAEQAGACAEADIAIAHQAIAHAEAKQAEALAAALQAAAMgEALQgEAKgIAHIgIAHQgEADgGACQgKAEgMAAIgLgBgAgQgmQgHADgFAGQgGAGgCAIQgDAHAAAIQAAAJADAIQACAHAGAGQAFAGAHADQAIAEAIAAQAJAAAIgEQAHgDAFgGQAFgGADgHQADgIAAgJQAAgIgDgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgIAAgIAEg");
	this.shape_1.setTransform(20.8,5.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaA1Ig3hWIAABWIgPAAIAAhpIATAAIA3BTIAAAAIAAhTIAPAAIAABpg");
	this.shape_2.setTransform(8.7,5.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIAgAAQAIAAAHACQAHABAFAEQAFADACAGQADAGAAAHQAAAJgDAFQgDAGgFADQgFADgHABQgHACgIAAIgQAAIAAAvgAgTgFIAPAAIAJgBIAIgDIAFgGQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgDIgIgBIgQAAg");
	this.shape_3.setTransform(-5,5.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLA3IgLgDQgKgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHQAHgIAKgEIALgDIALgBQAMAAAKAEQAGACAEADIAIAHQAIAHAEAKQAEALAAALQAAAMgEALQgEAKgIAHIgIAHQgEADgGACQgKAEgMAAIgLgBgAgQgmQgHADgFAGQgGAGgCAIQgDAHAAAIQAAAJADAIQACAHAGAGQAFAGAHADQAIAEAIAAQAJAAAIgEQAHgDAFgGQAFgGADgHQADgIAAgJQAAgIgDgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgIAAgIAEg");
	this.shape_4.setTransform(-16.1,5.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbA1IAAgxIg1AAIAAAxIgPAAIAAhpIAPAAIAAAsIA1AAIAAgsIAPAAIAABpg");
	this.shape_5.setTransform(-27.9,5.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgTA0QgKgEgGgHIALgKQAFAFAFAEQAHADAHAAIAHgBQAEgBADgCQADgCABgEQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgEIgIgEIgLgDQgEgBgFgEQgEgDgCgFQgCgFAAgHQAAgIADgGQADgGAGgDQAEgEAHgCQAGgCAHAAIAJABIAHADQAJADAFAFIgLALQgDgFgFgCQgGgDgHAAIgGABIgGADIgGAFQgBAEAAAEQAAAEABADIAFAFIAHAEIAIADIALADIAKAFQAEADADAGQADAFAAAIQAAAIgDAGQgEAGgEAEQgGAEgHACQgGACgGAAQgKAAgJgEg");
	this.shape_6.setTransform(-37.7,5.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-44,-6.2,88,22.4), null);


(lib.nineteengrapes_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteengrapes();
	this.instance.parent = this;
	this.instance.setTransform(-42.5,-75.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteengrapes_1, new cjs.Rectangle(-42.5,-75.5,85,151), null);


(lib.nineteencrackers_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencrackers();
	this.instance.parent = this;
	this.instance.setTransform(-15.5,-49.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencrackers_1, new cjs.Rectangle(-15.5,-49.5,31,99), null);


(lib.nineteencocktail_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencocktail();
	this.instance.parent = this;
	this.instance.setTransform(-55.5,-113);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencocktail_1, new cjs.Rectangle(-55.5,-113,111,226), null);


(lib.nineteencheese = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenchease();
	this.instance.parent = this;
	this.instance.setTransform(-92.5,-64);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencheese, new cjs.Rectangle(-92.5,-64,185,128), null);


(lib.nineteenbottomright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentomatoes();
	this.instance.parent = this;
	this.instance.setTransform(-84.5,-118);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteenbottomright, new cjs.Rectangle(-84.5,-118,169,236), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.269,0.269);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.269,0.269);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.269,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14,23.7,0.269,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(6.1,23.7,0.269,0.269);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.269,0.269);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.269,0.269);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.269,0.269);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.269,0.269);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-5.6,8.1,0.269,0.269);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.269,0.269);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(29.6,8.1,0.269,0.269);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-20.1,-9.9,0.269,0.269);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.269,0.269);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.269,0.269);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.269,0.269);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-47,-47,94,94), null);


(lib.holidayplatters = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape.setTransform(129.7,50.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag6BgQgKgDABgJQgBgGAKgEIAFgCQAFgDACgHQADgGAAgOIgBgOIAAgPIAAgMQAAgigCgLQgCgKgDgDIgJgEQgMgDABgHQAAgEADgEQADgDAJgDIAagIIARgEQAJAAADAaIABAEIABABQAJgQAMgIQALgIAKAAQAOAAAIAIQAHAIABAOQgBANgFAIQgGAIgMAAIgKgCIgIgGIgDgIQgDgEgCAAQgOAAgFASQgEASAAA6QAAARACAIQACAJAFACIAHADQAMADAAAJQAAAGgKAEQgLADgaAAQgeAAgJgDg");
	this.shape_1.setTransform(112.6,50.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAbAbQAaAbAAArQAAAsgcAeQgdAegpAAQgqAAgcgdgAgkg5QgMAQAAAaQAAAlAQAaQAQAaAXAAQATAAAMgQQALgQAAgbQAAgkgPgaQgSgagWAAQgSAAgMAQg");
	this.shape_2.setTransform(93.9,50.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABICIQgKgEAAgIQAAgIAMgEIAIgFQAEgCABgJQABgIAAgaIAAgKIAAhSIgBgxIgYBAQg5CUgMAAQgGAAgMgUQgLgVgag+IgrhhIgCBLIAAA1IABAjQABAJADACIAIAFQANAEAAAIQAAAIgKAEQgKADgYABQgVAAgJgFQgKgDAAgIQAAgHALgFQAKgFABgDQADgKADgyQADgxAAg8IAAgHQgBgUgBgHQgCgHgEgDIgJgDQgNgFAAgIQAAgIAJgDQAJgCAcAAIAcAAIAHABQADADAPAjIALAbIAFAOQAuB0AEAAQAEAAARgqQASgpAYhEIADgMQAHgVAHgHQADgCAHgCIAbgBQAaAAAIACQAJADAAAIQAAAIgLAEIgGACQgFAEgDAHQgBAHAAAeIABBuQACAxADAIQABAEAJADIADACIAIAEQACADAAAEQAAAIgLAEQgKADghABQgcgBgLgDg");
	this.shape_3.setTransform(65.6,46.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("Ah0B1QgkgcAAgsQAAgaALgSQAMgSAZgSIABgBQgIgJgEgJQgFgKABgKQAAgeAWgUQAWgTAjAAQAYAAAQAJQAQAJAAAMQAAAEgEAEQgDADgGAAIgPgFQgOgFgLAAQgQAAgJAKQgJAKAAARQAAAHACAGQADAGAEAFQAFADAJAFIAMADIADACIABAEQAAAEgGAHQgIAIgGAAIgJgBIgMgGQgLAKgGAOQgGANAAARQAAAlAZAYQAXAYAmAAQAfAAATgQQATgRAAgaQAAgPgHgLQgJgJgNAAQgNAAgIAIQgJAHAAANIAAAEIAAACIgCAAIgEABQgGAAgFgFQgEgGAAgJQAAgcBVgnIAFgDQAXgKALgMQAMgMAAgNQAAgJgFgFQgFgFgLABIgHABIgHAAQgEAAgDgCQgDgDABgEQAAgJAKgGQALgFAQAAQAVAAAMALQAMALAAAUQAAAYgVAUQgUATgsAQQASAIAKAOQAJAOAAAUQAAAPgGAOQgFAOgMALQgRATgbAKQgaAKgiAAQg6gBgkgbg");
	this.shape_4.setTransform(22,46.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgOBlIgVgFIgGAFIgFABIgEgBIgEgDQgHgFgFgQQgFgQAAgOQAAgGACgEQAEgEAFgBQAIABAKAPIAHAMQAGAIAKAEQAKAEAKABQANgBAIgGQAHgGAAgLQAAgQgfgQIgMgGQgegPgKgLQgLgNAAgSQAAgaASgPQARgQAdAAIAMAAIAOADIAJgEIAGgBQAJABAJAPQAJAPAAAQQAAAHgDAFQgCADgHAAQgDAAgFgDQgFgEgFgKQgIgMgHgEQgIgFgLAAQgKAAgHAGQgHAHABAKQAAAIAGAHQAIAHAXAMIACABQA2AagBAgQABAagVATQgVASgfAAg");
	this.shape_5.setTransform(-14.4,50.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag6BgQgKgDAAgJQAAgGAKgEIAFgCQAFgDACgHQADgGAAgOIgBgOIAAgPIAAgMQAAgigCgLQgCgKgDgDIgJgEQgMgDABgHQAAgEADgEQADgDAJgDIAagIIARgEQAJAAADAaIABAEIABABQAJgQALgIQAMgIAKAAQAOAAAIAIQAHAIABAOQgBANgGAIQgFAIgMAAIgKgCIgIgGIgDgIQgDgEgCAAQgOAAgFASQgEASAAA6QAAARACAIQACAJAFACIAHADQAMADAAAJQAAAGgKAEQgLADgaAAQgeAAgJgDg");
	this.shape_6.setTransform(-29.6,50.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_7.setTransform(-47.6,50.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgJB0QgKgDgHgGQgHgHgCgKQgEgLAAgdIAAhnIgSAAIgFgBIgBgFIAAgFQgBgGAVgRIAIgHIAHgHQAUgRAIAAIAEABQADACAAADIAAAkIArAAQAFAAACACQACACgBAFIAAAFQAAAFgCACQgCACgEAAIgnAAIgDACIgCAEIAABfQAAAZAFAHQADAGAMAAQAGAAAJgDIAOgDQAEAAADACQACADABAEQgBAKgQAKQgQAKgVAAQgLAAgJgDg");
	this.shape_8.setTransform(-64.6,48.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgDgLAAgdIAAhnIgSAAIgFgBIgCgFIAAgFQAAgGAVgRIAHgHIAIgHQAUgRAHAAIAFABQADACAAADIAAAkIArAAQAFAAACACQABACAAAFIAAAFQAAAFgBACQgCACgFAAIgnAAIgEACIgBAEIAABfQAAAZAFAHQADAGAMAAQAGAAAJgDIAOgDQAEAAADACQADADAAAEQAAAKgQAKQgRAKgVAAQgLAAgKgDg");
	this.shape_9.setTransform(-78.3,48.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgSAXgMQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAGQABAFAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_10.setTransform(-95.3,50.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AggCLQgJgDAAgJQgBgGAJgDIAKgGQADgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgCgPQgBgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAFgDANgFIAagHIATgDQAGAAACADQACAEABAKIAAAOQgDBFAABGIABBBQACAOADAEIAKAGQAKADgBAIQAAAGgJAEQgKADgZAAQgdAAgJgDg");
	this.shape_11.setTransform(-111.6,45.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AhjCJQgLgEAAgIQAAgIALgEIAJgFQAEgCACgYQABgWABg9IgChIQgBgdgDgDQgDgDgJgEQgKgFAAgHQAAgHAFgEQAGgDAMAAIAVABIAVAAIAngBIAfgBQArAAAWASQAVASAAAmQAAAogbAWQgbATgyABQgTAAAAgNQAAgNAQAAQAYAAAQgNQAPgNAAgdQgBgagPgMQgQgNgegBQgOABgGACQgGACgBAFIgDASIgBAoIAABUIACA3QABAPAEADIAIAEQAMAEAAAIQAAAIgLAEQgKADgfABQgegBgKgDg");
	this.shape_12.setTransform(-127.7,46.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgVA7QgDgCAAgDIAEgHIAEgGIALgVQAEgKAAgEIgBgFIgHgDQgKgEgEgHQgFgHAAgKQAAgNAIgIQAIgJAMAAQAMAAAJALQAIALAAASQAAANgFANQgGAOgMAVIgKAPQgEAFgDAAQgFAAgFgCg");
	this.shape_13.setTransform(100,14.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgOBlIgUgFIgHAFIgFABIgEgBIgEgDQgGgFgGgQQgGgQABgOQAAgGACgEQAEgEAFAAQAJgBAJAQIAIAMQAFAIAKAEQAKAEALABQAMgBAIgGQAHgGAAgLQAAgQgggQIgLgGQgdgPgLgLQgLgNAAgSQAAgaARgPQASgQAcAAIANAAIANADIAKgEIAGgBQAJABAJAPQAJAPAAAQQAAAHgCAFQgEADgFAAQgEAAgFgDQgEgEgGgKQgIgMgHgEQgIgFgLAAQgKAAgHAGQgHAHAAAKQABAIAGAHQAIAHAXAMIACABQA1AaABAgQAAAagVATQgVASgeAAg");
	this.shape_14.setTransform(85.7,4.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_15.setTransform(67.3,4.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgDgLAAgdIAAhnIgSAAIgFgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQABACABAFIAAAFQAAAFgCACQgCACgFAAIgnAAIgEACIgBAEIAABfQAAAZAFAHQADAGAMAAQAGAAAKgDIANgDQAEAAADACQADADAAAEQAAAKgQAKQgRAKgVAAQgLAAgKgDg");
	this.shape_16.setTransform(50.3,2.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AghCKQgKgDAAgJQAAgGAKgEIAEgCQAGgDABgGQACgHAAgOIAAgNIAAgQIAAgUQAAgegCgJQgBgJgEgCIgJgDQgMgEAAgGQABgFADgDQAEgEAIgDIAdgJIATgEQAGAAACAEQACAEAAAIIAAAMIAAAJIgCAwIAAABIAAAwQAAASABAIQACAHAFACIAHAEQAKADAAAIQAAAHgKADQgJADgZAAQgdAAgJgDgAgXhhQgIgGAAgLQAAgLAJgHQAJgIANAAQAMAAAIAHQAIAHAAALQAAAKgJAIQgJAHgNAAQgMAAgIgHg");
	this.shape_17.setTransform(37.8,0.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AgOCMIgmgCIgSABIgWAAQgNAAgIgEQgGgDAAgHQAAgIAKgDQAKgFACgCQADgEACgdIABhLIgBhIQgCgdgDgDQgCgDgKgEQgKgFAAgHQAAgHAGgEQAFgDAMAAIAVABIAWAAIAngBIAegBQAqAAAWARQAWARAAAhQAAAagPARQgRAQgdAFQAmAEAUASQAVASAAAgQAAAkgZAVQgaATguABgAgdhvQgGABgCADQgDAFgBATIgCA3IAABQIACAmQABAKADAGQACAEAJADQAKACAQAAQAggBAQgNQAQgNAAgZQAAgbgSgNQgTgNgjgBQgQABAAgLQAAgOAQAAQAaAAAQgMQAQgLAAgaQAAgYgPgNQgQgMgeAAg");
	this.shape_18.setTransform(19,0.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AggCLQgJgDAAgJQAAgGAIgDIAKgGQADgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgCgPQgBgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAFgDANgFIAagHIATgDQAGAAACADQACAEAAAKIAAAOQgCBFAABGIABBBQACAOADAEIAKAGQAKADgBAIQAAAGgJAEQgKADgZAAQgdAAgJgDg");
	this.shape_19.setTransform(-10.4,0);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AggCLQgJgDAAgJQAAgGAIgDIAKgGQADgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgCgPQgBgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAFgDANgFIAagHIATgDQAGAAACADQACAEAAAKIAAAOQgCBFAABGIABBBQACAOADAEIAKAGQAKADgBAIQAAAGgJAEQgKADgZAAQgdAAgJgDg");
	this.shape_20.setTransform(-21.2,0);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgTAXgLQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_21.setTransform(-36.4,4.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AicBgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgCgKgDgDIgJgEQgMgDAAgHQAAgEAEgDIALgHIAdgJIATgEQAFAAADADQACADABAHIAAALIAAABIAAACIACABIABAAIAAgBIAEgDIADgDQAXgVAYAAQAJAAAIADQAJADAHAEQAHAGAHAIQAHAJABAAQADAAAFgGIAJgJQAMgLAKgDQAJgEAMAAQAWAAAQAJQARAJAIAQQAJASAAA4IAAATIAAALIAAAJQAAAKABAFQACAFAGADIAEACQAKAEAAAGQAAAJgJADQgJACgeAAQgcAAgJgCQgJgEAAgGQgBgIAKgEIAIgDQAEgDADgJQACgKAAgXQgBg4gHgQQgJgPgTAAQgXAAgKAUQgKAUAAAuIAAAKQAAAVACAGQACAHAFADIAGACQAJAEAAAGQAAAJgJADQgJACgeAAQgZAAgKgCQgJgEAAgGQAAgIAJgDIAIgEQAEgCACgIQACgIgBgWQAAg8gHgQQgIgQgVAAQgKAAgJAGQgJAHgGAKQgEAIgBARQgCAOgBAlQABASACAGQABAHAEACIAHAEQALADgBAIQAAAGgJAEQgJADgaAAQgdAAgKgDg");
	this.shape_22.setTransform(-64.9,4.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AgvCMQgWgGgOgIQgHgEgFgQQgFgRAAgWQAAgIAEgGQADgEAGAAQAJAAAKASIAEAIQANAVAOAKQAPAJATAAQAVAAAPgMQAPgNAAgSQAAgbg6gZIgFgDQgwgTgOgSQgQgQAAgcQAAgiAagWQAZgXApAAIAWACIAbAGIAIgFIAGgCQAFAAADADQAFADADAIQAHALAEANQAEAMAAAKQAAAGgEAEQgDAEgFAAQgKAAgKgOIgCgEQgMgPgNgGQgNgHgQAAQgVAAgMAKQgMAKAAASQAAAPAKALQAKALApARIAJADQAiAPAPANQALAKAFANQAGANAAAPQAAAogbAWQgcAWgxAAQgXAAgVgEg");
	this.shape_23.setTransform(-93.7,0.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("AhYB/QgKgHABgNQAAgKAGgGQAHgHAJAAIAJACIAGADIAFAIQAFAHAEABQAJgBALgOQAKgOAAgPQAAgRgOgeIgCgFIgehDIgSglQgEgHgLgGQgHgCgCgCQgDgEABgDQgBgJALgDQAKgEAcAAQAcAAAKAEQAKADgBAHIgBAGIgDAEIgIADQgHADAAAEIAEAOIAPAnIAQAkQAFAJACAAQACAAAFgJIAMgfIAPgmQAFgOgBgFQAAgFgLgGQgLgGABgFQgBgHAKgDQAIgCAWgBQAYAAAIAEQAHADABAHQAAAHgMADIgHADQgLAFgNAhIgGAPIgYA+QggBQgTAZQgVAXgcAAQgOAAgJgIg");
	this.shape_24.setTransform(58.3,-37.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgTAXgLQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_25.setTransform(38.4,-41.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E47").s().p("AhUB1QgXgaAAgqQAAgvAbgdQAageApABIANABQAGACAEAEQADAEAAAGQAAAJgNABIgFgBIgFAAQgWgBgMATQgNAQAAAeQAAAhAOAVQAOATAWAAQATABALgLQALgMAAgWIAAg0IAAhZQAAgNgCgFQgDgGgHgCIgFgCQgMgDAAgHQAAgFAFgEQAEgEAPgFIAWgGIASgCQAGAAADAEQADADAAAJIAAAJIgCB3IABBRQABASADADIAOAEQAKADAAAGQAAAKgcAIIgTAGIgPABQgFAAgDgDQgCgCAAgHIAAgJIgBgEIgBgCIgGAEIgIAHQgMAIgKAFQgLAEgMAAQgkAAgXgag");
	this.shape_26.setTransform(17,-45.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E47").s().p("AghCKQgKgDAAgJQAAgGAKgEIAEgCQAGgDABgGQACgHAAgOIAAgNIAAgQIAAgUQAAgegCgJQgBgJgEgCIgJgDQgMgEAAgGQAAgFAEgDQADgEAJgDIAdgJIAUgEQAFAAACAEQADAEAAAIIAAAMIgBAJIgCAwIAAABIAAAwQAAASACAIQACAHADACIAIAEQAJADAAAIQAAAHgJADQgKADgZAAQgcAAgJgDgAgXhhQgJgGAAgLQAAgLAKgHQAJgIANAAQAMAAAIAHQAIAHAAALQAAAKgJAIQgJAHgNAAQgMAAgIgHg");
	this.shape_27.setTransform(-0.7,-45.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#006E47").s().p("AggCLQgJgDAAgJQAAgGAIgDIAKgGQADgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgCgPQgBgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAFgDANgFIAagHIATgDQAGAAACADQACAEAAAKIAAAOQgCBFAABGIABBBQACAOADAEIAKAGQAKADgBAIQAAAGgJAEQgKADgZAAQgdAAgJgDg");
	this.shape_28.setTransform(-11.8,-45.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAaAbQAbAbAAArQAAAsgcAeQgdAegqAAQgpAAgcgdgAgkg5QgMAQAAAaQAAAlARAaQAQAaAWAAQATAAAMgQQAMgQAAgbQAAgkgQgaQgRgagXAAQgTAAgLAQg");
	this.shape_29.setTransform(-27.7,-41.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#006E47").s().p("AArCIQgLgEAAgIQAAgIAMgEIAJgFQADgCACgMIABgtIAAgbIgCgIQgCgDgKgCQgJgBgkgBIgoABQgMABgDAEIgCAFIAAAPIAAAQIAAAtQACAMADACIAIAFQAMAEABAIQAAAIgLAEQgLADgfABQgdgBgLgDQgLgEAAgIQAAgIAMgEIAJgFQADgDACgYQACgYAAg6IgChIQgCgdgBgDQgCgDgLgEQgKgFAAgHQAAgIAIgDQAJgCAjAAQAhAAAKACQAIADABAIQgBAHgMAGIgIADQgDADgCAMIgBA5QAAAIAIACQAGADAdABIAPAAIApgCQAMgBADgDIADgDIAAgIIAAgJIgBgvQgCgKgDgDIgJgDQgMgGAAgHQAAgIAJgDQAJgCAjAAQAiAAAJACQAIADAAAIQAAAIgMAFIgJADQgDADgCAaQgCAbAAAzIACBKQABAdACAEQACADALAFQAKADAAAIQAAAIgLAEQgKADgeABQgggBgKgDg");
	this.shape_30.setTransform(-53.2,-45.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayplatters, new cjs.Rectangle(-142,-70.8,284,141.7), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgWVgteMAsrAAAMAAABa9MgsrAAAg");
	this.shape.setTransform(0,0,1.045,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-300.5,301,601), null);


(lib.fourteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.crowdpleasing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgOBlIgUgFIgHAFIgFABIgEgBIgEgDQgGgFgGgQQgGgQABgOQAAgGACgEQAEgEAFAAQAJAAAJAPIAIAMQAFAIAKAEQAKAEALABQAMgBAIgGQAHgGAAgLQAAgQgggQIgLgGQgdgPgLgLQgLgNAAgSQAAgaARgPQASgQAcAAIANAAIANADIAKgEIAGgBQAJABAJAPQAJAPAAAQQAAAHgCAFQgEADgFAAQgEAAgFgDQgEgEgGgKQgHgMgIgEQgIgFgLAAQgKAAgHAGQgHAHAAAKQABAIAGAHQAIAHAXAMIACABQA1AaABAgQAAAagVATQgVASgeAAg");
	this.shape.setTransform(127.6,27.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag6BgQgJgDAAgJQAAgGAJgEIAFgCQAFgDACgHQACgGAAgOIAAgOIAAgPIAAgMQAAgigCgLQgBgKgEgDIgJgEQgMgDAAgHQAAgEAEgEQADgDAJgDIAagIIARgEQAKAAACAaIABAEIABABQAKgQALgIQAKgIALAAQAOAAAIAIQAHAIAAAOQAAANgFAIQgHAIgKAAIgKgCIgIgGIgFgIQgCgEgCAAQgOAAgEASQgFASAAA6QAAARACAIQABAJAGACIAHADQAMADAAAJQAAAGgLAEQgKADgaAAQgeAAgJgDg");
	this.shape_1.setTransform(112.4,27.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_2.setTransform(94.4,27.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgDgLAAgdIAAhnIgSAAIgFgBIgCgFIAAgFQAAgGAVgRIAHgHIAIgHQAUgRAHAAIAFABQADACAAADIAAAkIArAAQAFAAACACQABACAAAFIAAAFQAAAFgBACQgCACgFAAIgnAAIgEACIgBAEIAABfQAAAZAFAHQADAGAMAAQAGAAAJgDIAOgDQAEAAADACQADADAAAEQAAAKgQAKQgRAKgVAAQgLAAgKgDg");
	this.shape_3.setTransform(77.4,25.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgKB0QgJgDgHgGQgHgHgDgKQgCgLAAgdIAAhnIgSAAIgGgBIgCgFIAAgFQABgGATgRIAIgHIAIgHQAUgRAHAAIAGABQACACAAADIAAAkIArAAQAFAAACACQABACABAFIAAAFQAAAFgCACQgDACgEAAIgoAAIgDACIgBAEIAABfQAAAZAEAHQAFAGALAAQAGAAAKgDIANgDQAEAAADACQACADAAAEQAAAKgPAKQgRAKgVAAQgLAAgKgDg");
	this.shape_4.setTransform(63.7,25.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgSAXgMQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_5.setTransform(46.7,27.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AggCLQgKgDABgJQAAgGAHgDIALgGQADgDABgMIABgmIAAgeIAAgkIAAgPQAAgwgBgPQgCgOgEgCIgMgEQgMgDAAgHQAAgFADgDQAEgDAOgFIAagHIATgDQAGAAACADQACAEAAAKIAAAOQgCBFAABGIABBBQABAOAEAEIALAGQAJADAAAIQAAAGgKAEQgKADgZAAQgcAAgKgDg");
	this.shape_6.setTransform(30.4,23);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhjCJQgMgEAAgIQAAgIANgEIAIgFQAEgCACgYQACgWAAg9IgChIQgBgdgDgDQgDgDgJgEQgLgFAAgHQABgHAFgEQAGgDAMAAIAUABIAXAAIAmgBIAfgBQArAAAWASQAWASgBAmQAAAogbAWQgaATgzAAQgTABAAgNQAAgNAQgBQAYABAQgNQAOgNAAgdQAAgagPgMQgQgNgegBQgOABgGACQgGACgCAFIgCASIAAAoIAABUIABA3QABAPAEADIAIAEQAMAEAAAIQAAAIgKAEQgLADgfABQgegBgKgDg");
	this.shape_7.setTransform(14.3,23.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_8.setTransform(-18.8,27.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgOBlIgVgFIgFAFIgGABIgEgBIgEgDQgHgFgFgQQgGgQAAgOQAAgGAEgEQADgEAFAAQAIAAAKAPIAHAMQAGAIAKAEQAKAEALABQANgBAHgGQAHgGAAgLQAAgQgggQIgKgGQgegPgLgLQgLgNAAgSQAAgaARgPQASgQAcAAIANAAIANADIAKgEIAGgBQAJABAKAPQAIAPAAAQQAAAHgCAFQgEADgFAAQgFAAgEgDQgFgEgFgKQgIgMgHgEQgIgFgKAAQgLAAgHAGQgGAHgBAKQAAAIAIAHQAGAHAXAMIADABQA1AaAAAgQAAAagUATQgVASgfAAg");
	this.shape_9.setTransform(-37.4,27.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_10.setTransform(-55.9,27.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_11.setTransform(-76.3,27.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAbCLQgKgEAAgHQAAgHAKgEIAHgDQAFgDACgIQABgIAAgVQAAg+gIgOQgHgQgVAAQgJAAgJAGQgKAGgFAKQgEAIgCAPQgCAPAAAmQAAATACAGQACAHADACIAIADQAKAEAAAHQAAAHgKAEQgJADgZAAQgfAAgIgEQgKgDAAgIQAAgHAKgDIAEgCQAFgDADgIQACgIAAgWIAAgfIAAgdIgBhYQgBgVgDgEQgCgCgMgEQgMgDAAgHQAAgFAGgDQAEgEARgHIATgFIASgCQAHAAACAEQADADAAAJIAAAIIgCBNIAAAKIABAEIADACIAEgEIAHgIQAKgKALgFQAJgEANAAQAhAAAQAVQAQAWAAAqIAAASIABAjIAAALQAAAKABAEQACAEAFADIAFACQAKADAAAHQAAAIgKADQgJAEgfAAQgZAAgJgDg");
	this.shape_12.setTransform(-98.3,23);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgdCHQgagKgUgRQgWgVgMgcQgMgdAAghQAAgbAIgYQAIgXAPgTQATgXAbgMQAcgMAfAAIAYACIAlAIIAEgCIAPgDIAGACIAFAGQAHAKAEAPQAEAOAAAMQAAAIgDAEQgDAEgGAAQgJAAgPgRIgMgOQgKgLgQgFQgPgGgSAAQgmAAgVAaQgWAaAAAtQAAA4AcAlQAbAlAqAAQARAAAPgGQAPgFAKgKIAJgLQAIgLAGAAQAGAAADAFQADAFAAAJQAAASgFALQgGAKgIAAIgCAAIgDgBQgSAKgSAEQgSAFgUAAQgbAAgagJg");
	this.shape_13.setTransform(-122.5,23.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AhHB+QgYgPgBgVQAAgKAGgGQAFgHAKAAQAJAAAEAFQAFAEACAKQAEAOANAIQAMAIAXAAQAZAAARgKQARgKAAgPQABgJgHgFQgGgFgMAAIgWACIgdABQgjAAgSgLQgTgMAAgPQAAgKAGgKQAIgIAOgJQgMgJgFgNQgHgMAAgPQAAggAZgUQAXgVAkAAIAUABIAdAGQAIAAAJgDIAUgMIAGAGIACAGQAAAIgGAIQgGAIgMAGIAGAPIACAQQABAggYAUQgYATgkAAIgVgBIgTgEIgFAHIgCAHQAAAJAJAFQAJAEATAAIAdgCIAegCQAbAAAOALQAPALAAAUQAAAfgfAVQgeAUguAAQglAAgYgPgAgfhfQgLAMAAATQAAAUAKAMQAKAMAQAAQAPAAALgMQALgMAAgUQAAgTgKgNQgLgMgQAAQgOAAgLANg");
	this.shape_14.setTransform(129,-15.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AheBgQgKgDAAgJQAAgGAKgEIAFgCQAFgDACgHQACgGAAgOIgBgOIAAgPIAAgTQAAgfgBgJQgCgJgEgCIgJgEQgLgDAAgHQAAgEADgEQAEgDAIgDIAcgJIAUgEQAFAAADAEQACADAAAGIAAAMIABACIABABIABAAIABgBIAEgDIAEgFQAVgTAYAAQAOAAANAGQAMAGAJALQAJAKAEAPQAEAOAAAgIAAAZIgBAMIAAALQAAAOACAFQACAGAFADIAFACQAJAEAAAGQAAAJgJADQgIACgeAAQgbAAgJgCQgKgEAAgGQAAgIAKgDIAHgEQAFgCACgJQABgIAAgVQAAg8gHgQQgIgQgVAAQgJAAgJAGQgKAHgFAKQgEAIgCAQQgBAOAAAmQAAASABAHQACAGAEACIAHAEQAKADAAAIQAAAGgKAEQgJADgZAAQgeAAgJgDg");
	this.shape_15.setTransform(106.5,-18.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgiCKQgJgDAAgJQAAgGAJgEIAGgCQAEgDACgGQADgHAAgOIgBgNIAAgQIAAgUQAAgegCgJQgBgJgEgCIgJgDQgMgEABgGQAAgFADgDQAEgEAIgDIAdgJIAUgEQAFAAADAEQACAEAAAIIAAAMIgBAJIgBAwIAAABIgBAwQAAASACAIQABAHAEACIAIAEQAJADAAAIQAAAHgJADQgKADgZAAQgcAAgKgDgAgXhhQgJgGAAgLQAAgLAKgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgMAAQgNAAgIgHg");
	this.shape_16.setTransform(89.5,-22.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgOBlIgVgFIgGAFIgFABIgEgBIgEgDQgGgFgGgQQgFgQAAgOQAAgGACgEQAEgEAFgBQAIAAAKAQIAHAMQAGAIAKAEQAKAEAKABQANgBAIgGQAHgGAAgLQAAgQgfgQIgMgGQgegPgKgLQgLgNAAgSQAAgaASgPQARgQAdAAIAMAAIAOADIAJgEIAGgBQAJABAKAPQAIAPAAAQQAAAHgDAFQgCADgHAAQgEAAgEgDQgFgEgFgKQgHgMgIgEQgIgFgLAAQgKAAgHAGQgHAHABAKQAAAIAGAHQAIAHAXAMIACABQA2AagBAgQABAagVATQgVASgfAAg");
	this.shape_17.setTransform(75.7,-18.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAiBbIgKgLIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgbQAAgeAXgRQAWgRApAAQAJAAAFACQAFADAAAIQAAALgNAAQgTAAgMAJQgMAJAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgIAAgVIAAhIQAAgRgIgKQgHgJgNAAQgJAAgIAEQgJAFgHAJIgEAEQgMAPgNAAQgIAAgEgEQgFgGAAgIQAAgTAXgLQAWgNAjAAQAVAAAPAGQAQAFAIALQAGAIACAMQADALAAAcIAAA9QAAALACAFQABAGAEABIAGACQANADAAAGQAAAJgNAJQgNAHgSAAQgIAAgKgKg");
	this.shape_18.setTransform(57.3,-18.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_19.setTransform(36.6,-18.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AggCLQgKgDAAgJQABgGAHgDIAKgGQAEgDACgMIABgmIAAgeIAAgkIAAgPQAAgwgCgPQgCgOgEgCIgMgEQgNgDAAgHQAAgFAFgDQADgDAOgFIAagHIATgDQAGAAADADQABAEAAAKIAAAOQgCBFAABGIACBBQAAAOADAEIAMAGQAIADABAIQAAAGgKAEQgKADgZAAQgdAAgJgDg");
	this.shape_20.setTransform(20.7,-22.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AhkCJQgKgEgBgIQABgIALgEIAJgFQAEgCACgYQACgWgBg9IgBhIQgCgdgCgDQgCgDgLgEQgKgFAAgHQAAgHAHgEQAFgDANAAIATABIAWAAIAogBIAdgBQAsAAAWASQAWASAAAmQAAAogbAWQgbATgzAAQgTABAAgNQAAgNAQgBQAYABAPgNQAPgNAAgdQAAgagPgMQgPgNgfgBQgOABgGACQgFACgCAFIgCASIgBAoIAABUIABA3QABAPADADIAJAEQAMAEAAAIQAAAIgLAEQgKADgfABQgegBgLgDg");
	this.shape_21.setTransform(4.5,-22.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AglAUQgGAAgCgCQgEgCAAgGIACgIIAFgLQADgFACgCQADgCAIAAIAKAAIAQAAIAhgBIAFAAQAGAAADACQADACgBAFQAAALgFAJQgGAJgJAAIgJAAIgLgBIgqACIgEAAg");
	this.shape_22.setTransform(-14.2,-18.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AhUB1QgXgaAAgqQAAgvAbgdQAageApABIANABQAGACAEAEQADAEAAAGQAAAJgNABIgFgBIgFAAQgWgBgMATQgNAQAAAeQAAAhAOAVQAOATAWAAQATABALgLQALgMAAgWIAAg0IAAhZQAAgNgCgFQgDgGgHgCIgFgCQgMgDAAgHQAAgFAFgEQAEgEAPgFIAWgGIASgCQAGAAADAEQADADAAAJIAAAJIgCB3IABBRQABASADADIAOAEQAKADAAAGQAAAKgcAIIgTAGIgPABQgFAAgDgDQgCgCAAgHIAAgJIgBgEIgBgCIgGAEIgIAHQgMAIgKAFQgLAEgMAAQgkAAgXgag");
	this.shape_23.setTransform(-31.6,-22.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("AALAVIgXg8QgLgbgJgFIgGgDQgLgEAAgHQAAgHAKgDQAKgEAeAAQAaAAAKAEQAJADAAAHIgBAGIgEAEIgGACQgIAEAAAEIADANIAQAoIARAlQAEAIADAAQACABAEgGIAIgRIAVgwQAHgTAAgGIgBgHIgFgFIgFgBQgJgEAAgGQAAgHAJgDQAIgEAYAAQAUAAAJAEQAIACAAAIQAAAHgKAEIgHACQgJAFgRAoIgEAJIgIASQgsBkgNgBQgNAAgihOgAhxALIgGgMIgMghQgNgggIgFIgGgDQgLgEAAgHQAAgHAJgDQAKgEAfAAQAbAAAJAEQAJADAAAHIgBAGIgDAEIgHACQgIAEAAAEIAFAQIAOAlIAQAkQAFAKADgBQAGABAFgMIAGgOIAFgGQACgCAFAAQAEAAADADQADADAAAEQAAAFgGALQgUAsgJAQQgJANgGAAQgOABgmhZg");
	this.shape_24.setTransform(-59.3,-18.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAaAbQAbAbAAArQAAAsgcAeQgdAegpAAQgqAAgcgdgAgkg5QgMAQAAAaQAAAlAQAaQARAaAWAAQATAAAMgQQAMgQAAgbQAAgkgQgaQgRgagXAAQgSAAgMAQg");
	this.shape_25.setTransform(-86.3,-18.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E47").s().p("Ag6BgQgKgDAAgJQAAgGAKgEIAFgCQAFgDACgHQACgGABgOIgBgOIAAgPIAAgMQAAgigBgLQgCgKgFgDIgIgEQgLgDAAgHQgBgEAEgEQADgDAJgDIAagIIARgEQAJAAAEAaIAAAEIABABQAJgQALgIQAMgIALAAQANAAAHAIQAJAIAAAOQAAANgHAIQgFAIgMAAIgKgCIgIgGIgDgIQgDgEgCAAQgNAAgGASQgEASAAA6QAAARABAIQADAJAFACIAIADQALADAAAJQAAAGgKAEQgMADgZAAQgeAAgJgDg");
	this.shape_26.setTransform(-104.1,-18.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E47").s().p("AgdCHQgagKgUgRQgWgVgMgcQgMgdAAghQAAgbAIgYQAIgXAPgTQATgXAbgMQAcgMAfAAIAYACIAlAIIAEgCIAPgDIAGACIAFAGQAHAKAEAPQAEAOAAAMQAAAIgDAEQgDAEgGAAQgJAAgPgRIgMgOQgKgLgQgFQgPgGgSAAQgmAAgVAaQgWAaAAAtQAAA4AcAlQAbAlAqAAQARAAAPgGQAPgFAKgKIAJgLQAIgLAGAAQAGAAADAFQADAFAAAJQAAASgFALQgGAKgIAAIgCAAIgDgBQgSAKgSAEQgSAFgUAAQgbAAgagJg");
	this.shape_27.setTransform(-125,-22.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.crowdpleasing, new cjs.Rectangle(-140.5,-47.9,281.1,95.8), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// rollover
	this.instance = new lib.seventeenrollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.2,-12.7,142.5,35.5);


// stage content:
(lib.halfpagebannernineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_70 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_227 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(70).call(this.frame_70).wait(157).call(this.frame_227).wait(2));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(150.3,301.6,1.456,0.919,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(229));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(229));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150.2,300,1.826,1,0,0,0,0.1,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(220));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,37);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.07,scaleY:1.07,alpha:1},6,cjs.Ease.get(1)).to({regX:0.1,regY:0.1,scaleX:1,scaleY:1,x:150.1,y:37.2},7,cjs.Ease.get(1)).wait(207));

	// order-now
	this.instance_3 = new lib.ordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,347.3);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(70).to({y:346.3},0).to({alpha:1},10).wait(149));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(150,346.8);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(70).to({alpha:1},10).wait(149));

	// cta-rectangle
	this.instance_4 = new lib.seventeenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,346.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(70).to({alpha:1},10).wait(149));

	// get-party-started
	this.instance_5 = new lib.partystarted();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,158.4);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(212).to({alpha:1},10).wait(7));

	// HOLIDAY-PLATTERS
	this.instance_6 = new lib.holidayplatters();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,246.9);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(212).to({alpha:1},10).wait(7));

	// Ready-toServe
	this.instance_7 = new lib.readytoserve();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,247.9);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(152).to({alpha:1},10).wait(40).to({alpha:0},5).wait(22));

	// PARTY-PERFECT CRUDITE
	this.instance_8 = new lib.partyperfect();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,247.9);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(102).to({alpha:1},10).wait(40).to({alpha:0},5).wait(72));

	// crowd-pleasing
	this.instance_9 = new lib.crowdpleasing();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,247.9);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(52).to({alpha:1},10).wait(40).to({alpha:0},5).wait(122));

	// cheese
	this.instance_10 = new lib.nineteencheese();
	this.instance_10.parent = this;
	this.instance_10.setTransform(92.5,64);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(15).to({alpha:1},10).wait(204));

	// crackers
	this.instance_11 = new lib.nineteencrackers_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(15.5,167.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(22).to({alpha:1},10).wait(197));

	// bottom-right
	this.instance_12 = new lib.nineteenbottomright();
	this.instance_12.parent = this;
	this.instance_12.setTransform(215.5,482);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(27).to({alpha:1},10).wait(192));

	// bottom-left
	this.instance_13 = new lib.nineteencocktail_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(55.5,465);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(34).to({alpha:1},10).wait(185));

	// top-right
	this.instance_14 = new lib.nineteengrapes_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(257.5,75.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(39).to({alpha:1},10).wait(180));

	// table
	this.instance_15 = new lib.fourteentable_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(229));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,290,300,613);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.jpg?1510757522030", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;